# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  # schedule: 
  #   - cron: '0 * * * *' // runs at the top of every hour
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # allows for manual start
  workflow_dispatch: 



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore

  # jobs run parallel 
  test: 
    runs-on: ubuntu-latest
    # awaits for the build job to end, before it is executed
    needs: build 

    steps:
    - name: checkout repositiory
      uses: actions/checkout@v4
       # already prepared action

    # steps are consecutively executed and can be already preapred actions or shell commands test
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies, buld and test
      run: |
        dotnet restore
        dotnet build --no-restore
        dotnet test --no-build --verbosity normal